# Configuración de la base de datos MySQL
db.url=jdbc:mysql://localhost:3306/pacienteHistoriaClinica?useSSL=false&serverTimezone=UTC
db.username=root
db.password=
db.driver=com.mysql.cj.jdbc.Driver

# Configuración del pool de conexiones
db.pool.initialSize=5
db.pool.maxActive=10
db.pool.maxIdle=5
db.pool.minIdle=2
db.pool.maxWait=10000

